### PR TITLE
Modify sample nginx config to include TLSv1.3

### PR DESCRIPTION
**Pull request by archaeme**

### CODE REVIEW

**Comment by Johann150** [comment]
I think it might be a good idea to use the certbot provided configuration snippet with
```
    include /etc/letsencrypt/options-ssl-nginx.conf;
```
But I'm not sure if that is always available or only if you used certbot's nginx capabilities at least once.

And it is of course not available if using neither letsencrypt nor certbot, but I reckon those people would be able to find out themselves what is currently considered safe?

**Comment by archaeme** [comment]
I usually borrow from Mozilla's SSL config generator, that has worked well for me in the past.
https://ssl-config.mozilla.org/

At a glance it does seem like certbot's nginx config snippet does match that of mozilla's ssl config for the most part.

**Comment by archaeme** [comment]
I decided to update it to match Mozilla's SSL config but I can opt for the certbot include if that's desired.

**Comment by Johann150** [comment]
I think this way has the advantage that it is nicer for people that do not (want to) use Let's Encrypt.

**Pull request merged**
