### PR TITLE
Ita lang update 12.119.2

### PR DESCRIPTION
**Pull request by tassoman**
- added install section
- added missing timelines page
- updated changelog and faqs (from :jp: )

### CODE REVIEW

**Comment by syuilo** [comment]
🙏

**Comment by tassoman** [comment]
グラーツィエ!

**Comment by tassoman** [comment]
@syuilo how I can route `/` to `/it/` when browser's language is one of _italian_ ? Now `/` route only to `/en/` :thinking:

**Comment by syuilo** [comment]
> @syuilo how I can route `/` to `/it/` when browser's language is one of _italian_ ? Now `/` route only to `/en/` 🤔

👀 
https://github.com/misskey-dev/misskey-hub/blob/21567fc32b87201431b14c2106dd25b2e5ea16c7/src/.vuepress/mitheme/src/client/layouts/Landing.vue#L243-L246

**Pull request merged**
