### PR TITLE
General improvements + many improvements for English version

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
*Only affects English version*
- Better wording
- Hide big Ai-chan
- Screenshots in English

*Affects all*
- More readable text
- Slightly more clear screenshot positioning
- Change `(c) ` to `©`
- Add alt text to images

### CODE REVIEW

**Comment by Johann150** [comment]
Not sure about the changes you made in `src/.vuepress/theme/layouts/Layout.vue`, there are generally single quotes in the JavaScript parts so I think the reformatting was unnecessary.
I think you could probably also implement the style tags that hide things better by adding them to the preamble. But there again not entirely sure why you are doing that.
Also don't fully agree with some of the rewording: Misskey is software and the platform is the Fediverse. Why `that'll make you ask why you weren't here already!`? I don't think we should "guilt trip" people when they visit our landing page.

**Comment by ThatOneCalculator** [comment]
As for the code formatting/single quotes, I think that was VSCode doing that, I'll see if I can reverse it

For the style tags, that seemed to be the best way to have modifications only for the English version, but I'm not the best at VuePress so if you can think of a better implementation. 

I'll admit that wording on the landing page was a bit much, I'll rework that today.

**Comment by ThatOneCalculator** [comment]
> I think you could probably also implement the style tags that hide things better by adding them to the preamble. 

@Johann150 Which file is the preamble again? ^^"

**Comment by Johann150** [comment]
My mistake, what I meant is apparently called "frontmatter".

**Comment by ThatOneCalculator** [comment]
@Johann150 I can't seem to find a way to add the style to Frontmatter just for the English version. Any suggestions?

**Comment by 4ioskd** [comment]
Fist of all, your many improvement commits should be seperated by each topics https://github.com/misskey-dev/misskey-hub/pull/76#issue-1222029827 and be seperately reopend these here. Your each commits are worth of discussions and lead to breaking changes for  **Misskey Official website**.  especially, "Better wording", "Hide big Ai-chan" and releted to src/.vuepress/theme/layouts/Layout.vue .
Your commits are too many to comment to each of them and have a discussion.

**Comment by ThatOneCalculator** [comment]
@4ioskd @syuilo see #79 #80 #81 #82

**Pull request closed without merging**
